SELECT MIN(dy) AS firstDay, MAX(dy) AS lastDay
FROM (
    SELECT DATE_ADD(CURRENT_DATE, INTERVAL id - DAYOFMONTH(CURRENT_DATE) DAY) AS dy
    FROM T100
    WHERE id <= DAY(LAST_DAY(CURRENT_DATE))
) AS X
WHERE DAYNAME(dy) = 'Monday';
