WITH RECURSIVE X(dy, cnt) AS (
    SELECT DATE_ADD(CURRENT_DATE(), INTERVAL 1 - DAYOFYEAR(CURRENT_DATE()) DAY) dy, 1
    UNION ALL
    SELECT DATE_ADD(dy, INTERVAL 3 MONTH), cnt + 1
    FROM X
    WHERE cnt + 1 <= 4
)

SELECT QUARTER(dy) QTR,
       dy Q_start,
       DATE_ADD(DATE_ADD(dy, INTERVAL 3 MONTH), INTERVAL -1 DAY) AS Q_end
FROM X
ORDER BY dy;
