SELECT 
  kc.TABLE_NAME,
  kc.COLUMN_NAME,
  kc.CONSTRAINT_NAME,
  kc.REFERENCED_TABLE_NAME,
  kc.REFERENCED_COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE kc
WHERE
  kc.REFERENCED_TABLE_SCHEMA = (SELECT DATABASE()) AND
  kc.REFERENCED_TABLE_NAME = 'EMP' AND
  kc.CONSTRAINT_NAME NOT IN (
    SELECT 
      i.INDEX_NAME
    FROM 
      INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
      INNER JOIN INFORMATION_SCHEMA.STATISTICS i ON tc.TABLE_SCHEMA = i.TABLE_SCHEMA
        AND tc.TABLE_NAME = i.TABLE_NAME
    WHERE 
      tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
      AND tc.TABLE_SCHEMA = kc.REFERENCED_TABLE_SCHEMA
      AND tc.TABLE_NAME = kc.REFERENCED_TABLE_NAME
  );
