DROP TABLE IF EXISTS DEPT_EAST;

CREATE TABLE DEPT_EAST (
    DEPTNO integer,
    DNAME VARCHAR(14),
    LOC VARCHAR(13)
);

INSERT INTO DEPT_EAST (deptno, dname, loc)
SELECT *
FROM DEPT
WHERE LOC IN ('NEW YORK', 'BOSTON');