DROP TABLE IF EXISTS DEPT_ACCIDENTS;

CREATE TABLE DEPT_ACCIDENTS (deptno INT, accident_name VARCHAR(20));

INSERT INTO DEPT_ACCIDENTS VALUES (10, 'BROKEN FOOT');
INSERT INTO DEPT_ACCIDENTS VALUES (10, 'FLESH WOUND');
INSERT INTO DEPT_ACCIDENTS VALUES (20, 'FIRE');
INSERT INTO DEPT_ACCIDENTS VALUES (20, 'FIRE');
INSERT INTO DEPT_ACCIDENTS VALUES (20, 'FLOOD');
INSERT INTO DEPT_ACCIDENTS VALUES (30, 'BRUISED GLUTE');


DELETE FROM EMP
WHERE deptno IN (
    SELECT deptno FROM DEPT_ACCIDENTS
    GROUP BY deptno
    HAVING COUNT(*) >= 3
    )